name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Job for Minify-JS
      - name: HTML/CSS/JS Minifier
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'scripts/src'
          output: 'scripts/build'
          
      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minify action'
          branch: ${{ github.ref }}