name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Job for Minify-JS
       - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:1.0.3
        with:
          directory: 'scripts/src'      # Optional
          output: 'scripts/build'  # Optional
          add_suffix: true     # Optional
          
      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minify-JS : Commit Pipeline'
          branch: ${{ github.ref }}